/*
 * This file is generated by jOOQ.
*/
package com.family.structure.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Employee implements Serializable {

    private static final long serialVersionUID = 1826902247;

    private Integer id;
    private String  name;
    private Integer modifyFlag;

    public Employee() {}

    public Employee(Employee value) {
        this.id = value.id;
        this.name = value.name;
        this.modifyFlag = value.modifyFlag;
    }

    public Employee(
        Integer id,
        String  name,
        Integer modifyFlag
    ) {
        this.id = id;
        this.name = name;
        this.modifyFlag = modifyFlag;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getModifyFlag() {
        return this.modifyFlag;
    }

    public void setModifyFlag(Integer modifyFlag) {
        this.modifyFlag = modifyFlag;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Employee (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(modifyFlag);

        sb.append(")");
        return sb.toString();
    }
}
