/*
 * This file is generated by jOOQ.
*/
package com.family.structure;


import com.family.structure.tables.Employee;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Family extends SchemaImpl {

    private static final long serialVersionUID = 610377642;

    /**
     * The reference instance of <code>family</code>
     */
    public static final Family FAMILY = new Family();

    /**
     * The table <code>family.employee</code>.
     */
    public final Employee EMPLOYEE = com.family.structure.tables.Employee.EMPLOYEE;

    /**
     * No further instances allowed
     */
    private Family() {
        super("family", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Employee.EMPLOYEE);
    }
}
