/*
 * This file is generated by jOOQ.
*/
package com.family.structure;


import com.family.structure.tables.Employee;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in family
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>family.employee</code>.
     */
    public static final Employee EMPLOYEE = com.family.structure.tables.Employee.EMPLOYEE;
}
